version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -DskipTests package
      - persist_to_workspace:
          root: ./
          paths:
            - target/

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn test

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build