version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -DskipTests package
      - persist_to_workspace:
          root: ./
          paths:
            - target/
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn test
  publish:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run:
          command: ./.circleci/push-to-nexus.sh
          environment:
            GPG_EXECUTABLE: GPG

workflows:
  version: 2.1
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
                - main
          context: Sonatype